CREATE DATABASE SCADA_AirHeater;
GO

USE SCADA_AirHeater;
GO

CREATE TABLE Tag (
    TagID INT IDENTITY PRIMARY KEY,
    TagName NVARCHAR(100) UNIQUE,
    Description NVARCHAR(200),
    Unit NVARCHAR(20),
    DataType NVARCHAR(20),
    IsActive BIT
);

CREATE TABLE Measurement (
    MeasurementID BIGINT IDENTITY PRIMARY KEY,
    TagID INT FOREIGN KEY REFERENCES Tag(TagID),
    TimestampUTC DATETIME2,
    Value FLOAT,
    QualityFlag NVARCHAR(20)
);
